[package]
name = "loader"
version = "0.1.0"
authors = ["Gaulthier Gain <firecracker-devel@amazon.com>"]
edition = "2018"
build = "../../build.rs"
license = "Apache-2.0"

[dependencies]
libc = ">=0.2.39"
serde = { version = ">=1.0.27", features = ["derive"] }
bincode = "1.3"
concat-string = "1.0.1"